# Generated by Django 4.0.4 on 2022-09-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_produit_imageproduit2'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='imageProduit3',
            field=models.ImageField(blank=True, null=True, upload_to='img3'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='imageProduit2',
            field=models.ImageField(blank=True, null=True, upload_to='img2'),
        ),
    ]
