# Generated by Django 4.0.4 on 2022-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_produit_imageproduit3_alter_produit_imageproduit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_sur', models.CharField(blank=True, max_length=100, null=True)),
                ('reduction', models.IntegerField(blank=True, null=True)),
                ('date_fin_promo', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='numero',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
