# Generated by Django 4.0.4 on 2022-09-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_promotion_produit_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='quantite',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
